### ISSUE TITLE
Saving Descriptive Text

### ISSUE THREAD

**Issue by jephkay23** [Spice-King/foundry-swnr#87]
When creating a custom item any text entered in the description vanishes as if not saved when closing the item record.

**Comment by RaaviArda** [comment]
Can confirm, using SWNR 0.5.3 on Foundry 10 patch 6 build 291
Pressing the Save button throws an error in console:
Uncaught (in promise) Error: data.description is not an active editor name!
[No packages detected]
    at BaseSheet.saveEditor (foundry.js:6060:46)
    at jR.save_onsavecallback (foundry.js:6102:39)
    at plugin.min.js:4:1197
    at jR.<anonymous> (plugin.min.js:4:1412)
    at commands.exec.<computed> (tinymce.min.js:4:358670)
    at iR.execCommand (tinymce.min.js:4:358116)
    at jR.execCommand (tinymce.min.js:4:383782)
    at Object.onAction (plugin.min.js:4:842)
    at theme.min.js:4:261255
    at theme.min.js:4:118394
    at theme.min.js:4:261224
    at theme.min.js:4:29516
    at N (theme.min.js:4:2455)
    at run (theme.min.js:4:29501)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141481
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141470)
    at Cr (theme.min.js:4:25368)
    at xr (theme.min.js:4:25213)
    at Sr (theme.min.js:4:25276)
    at e (theme.min.js:4:86243)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141389
    at theme.min.js:4:141410
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141359)
    at theme.min.js:4:138209
    at HTMLDivElement.<anonymous> (theme.min.js:4:13954)
